# Use Node base image
FROM node:20

# Set app directory
WORKDIR /app

# Copy package files and install
COPY package*.json ./
RUN npm install

# Copy the rest of the app
COPY . .

# Expose backend port (change if needed)
EXPOSE 8000

# Default command
CMD ["npm", "start"]
